# Generated by Django 6.0 on 2025-12-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_dish_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'ordering': ['username'], 'verbose_name': 'cook', 'verbose_name_plural': 'cooks'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name']},
        ),
    ]
